# Makefile.deps created Thu Jun  5 15:05:37 PDT 2014
debug.o: debug.c debug.h
hashset.o: hashset.c debug.h hashset.h strhash.h
strhash.o: strhash.c strhash.h
spellchk.o: spellchk.c debug.h hashset.h yyextern.h
